set mouse_enabled false
set column_ratios 3,5
set automatically_count_files false
map / console scout -fltie%space
set collapse_preview false
set use_preview_script false
set preview_directories true
set preview_files true
set preview_max_size 262144
set vcs_aware false
map S quit
# Linux/default setup:
# map C shell -f code .

# Windows/WSL setup:
# -map C shell -f code .
map C shell -f "/mnt/c/Program Files/Microsoft VS Code/bin/code" .
map O shell /home/cady/.opencode/bin/opencode .
