#!/usr/bin/env bash
# Switch the whole environment palette (nvim, tmux, opencode, terminal, pygments).
# Usage: theme <neon|light>
set -euo pipefail

repo="$HOME/dotfiles"
name="${1:?usage: theme <neon|light>}"
data="$repo/themes/$name.json"
pal="${XDG_STATE_HOME:-$HOME/.local/state}/system-theme"

[ -f "$data" ] || { echo "unknown theme: $name" >&2; exit 1; }
mkdir -p "$pal"

python3 - "$repo" "$data" <<'PYEOF'
import json, os, string, sys

repo, data_path = sys.argv[1], sys.argv[2]
home = os.path.expanduser("~")
with open(data_path) as f:
    t = json.load(f)
nv, tx, wt, op = t["nvim"], t["tmux"], t["wt"], t["name"]

# 1) nvim palette module
lines = ["-- Generated by scripts/theme.sh from themes/%s.json; do not edit by hand." % op, "return {"]
lines.append('\tvariant = "%s",' % nv["variant"])
for k in ("fg","muted","green","cyan","yellow","orange","magenta","purple","red","select","linenr"):
    lines.append('\t%s = "%s",' % (k, nv[k]))
lines.append("}")
with open(f"{repo}/config/nvim/lua/config/palette.lua", "w") as f:
    f.write("\n".join(lines) + "\n")

# 2) tmux palette overlay
tmux = f'''# Generated by scripts/theme.sh from themes/{op}.json; do not edit by hand.
set -g status-style bg=default,fg='{tx["text"]}'
set -g status-left '#[fg={tx["session"]}]#S(#[fg={tx["telemetry"]}]#(~/dotfiles/scripts/tmux-telemetry.sh)#[fg={tx["session"]}])'
set -g status-right '#[fg={tx["path"]}]#(~/dotfiles/scripts/tmux-path-status.sh "#{{pane_current_path}}")#(~/dotfiles/scripts/tmux-git-bracket.sh open "#{{pane_current_path}}")#[fg={tx["git_problem"]}]#(~/dotfiles/scripts/tmux-git-status.sh "#{{pane_current_path}}")#[fg={tx["path"]}]#(~/dotfiles/scripts/tmux-git-bracket.sh close "#{{pane_current_path}}")#[fg={tx["text"]}] '
setw -g window-status-format '#[fg={tx["text"]}]#W'
setw -g window-status-current-format '#[fg={tx["current_window"]},bold]#W'
'''
with open(f"{home}/.tmux.palette.conf", "w") as f:
    f.write(tmux)

# 3) shell env for pygmentize
with open(f"{home}/.config/palette-env.sh", "w") as f:
    f.write("# Generated by scripts/theme.sh\nexport PYGMENTIZE_STYLE=%s\n" % t["pygments"])

# 4) opencode theme reference (opencode.json + tui.json + ocv-tui.json; live + repo)
oc_files = [
    f"{home}/.config/opencode/opencode.json",
    f"{repo}/config/opencode/opencode.json",
    f"{home}/.config/opencode/tui.json",
    f"{repo}/config/opencode/tui.json",
    f"{repo}/config/opencode/ocv-tui.json",
]
for path in oc_files:
    try:
        with open(path) as f:
            oc = json.load(f)
    except FileNotFoundError:
        continue
    oc["theme"] = t["opencode_theme"]
    with open(path, "w") as f:
        json.dump(oc, f, indent=2)
        f.write("\n")

# sync theme json files into the live opencode config
import shutil
themes_dst = f"{home}/.config/opencode/themes"
os.makedirs(themes_dst, exist_ok=True)
for tf in os.listdir(f"{repo}/config/opencode/themes"):
    if not tf.endswith(".json"):
        continue
    src, dst = f"{repo}/config/opencode/themes/{tf}", f"{themes_dst}/{tf}"
    if os.path.exists(dst) and os.path.samefile(src, dst):
        continue
    shutil.copy(src, dst)

# 5) Windows Terminal colorscheme
wt_path = "/mnt/c/Users/z005561w/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
with open(wt_path) as f:
    s = json.load(f)
scheme = {"name": t["wt_scheme"], "cursorColor": wt["foreground"]}
for key, val in {
    "background":"background","foreground":"foreground","black":"black","red":"red","green":"green",
    "yellow":"yellow","blue":"blue","purple":"purple","cyan":"cyan","white":"white",
    "brightBlack":"brightBlack","brightRed":"brightRed","brightGreen":"brightGreen","brightYellow":"brightYellow",
    "brightBlue":"brightBlue","brightPurple":"brightPurple","brightCyan":"brightCyan","brightWhite":"brightWhite",
    "selectionBackground":"selectionBackground",
}.items():
    if val in wt:
        scheme[key] = wt[val]
schemes = s.setdefault("schemes", [])
for i, ex in enumerate(schemes):
    if ex.get("name") == t["wt_scheme"]:
        schemes[i] = scheme
        break
else:
    schemes.append(scheme)
for p in s.get("profiles", {}).get("list", []):
    if p.get("name") == "Ubuntu" and p.get("colorScheme"):
        p["colorScheme"] = t["wt_scheme"]
        p.setdefault("opacity", 85)
with open(wt_path, "w") as f:
    json.dump(s, f, indent=4)
PYEOF

tmux source-file "$HOME/.tmux.palette.conf" 2>/dev/null || true
echo "theme: $name (restart nvim + opencode to apply)"
