#!/usr/bin/env bash
# Switch the whole environment palette (nvim, tmux, opencode, terminal, pygments).
# Usage: theme <neon|light>
set -euo pipefail

repo="$HOME/dotfiles"
name="${1:?usage: theme <neon|light>}"
data="$repo/color-schemes/$name.json"
pal="${XDG_STATE_HOME:-$HOME/.local/state}/system-theme"

[ -f "$data" ] || { echo "unknown theme: $name" >&2; exit 1; }
mkdir -p "$pal"

python3 - "$repo" "$data" <<'PYEOF'
import json, os, string, sys

repo, data_path = sys.argv[1], sys.argv[2]
home = os.path.expanduser("~")
with open(data_path) as f:
    t = json.load(f)
nv, tx, wt, op = t["nvim"], t["tmux"], t["wt"], t["name"]

# 1) nvim palette module
lines = ["-- Generated by scripts/theme.sh from color-schemes/%s.json; do not edit by hand." % op, "return {"]
lines.append('\tvariant = "%s",' % nv["variant"])
for k in ("fg","muted","green","cyan","yellow","orange","magenta","purple","red","select","linenr"):
    lines.append('\t%s = "%s",' % (k, nv[k]))
lines.append("}")
with open(f"{repo}/config/nvim/lua/config/palette.lua", "w") as f:
    f.write("\n".join(lines) + "\n")

# 2) tmux palette overlay
tmux = f'''# Generated by scripts/theme.sh from color-schemes/{op}.json; do not edit by hand.
set -g status-style bg=default,fg='{tx["text"]}'
set -g status-left '#[fg={tx["session"]}]#S(#[fg={tx["telemetry"]}]#(~/dotfiles/scripts/tmux-telemetry.sh)#[fg={tx["session"]}])'
set -g status-right '#[fg={tx["path"]}]#(~/dotfiles/scripts/tmux-path-status.sh "#{{pane_current_path}}")#(~/dotfiles/scripts/tmux-git-bracket.sh open "#{{pane_current_path}}")#[fg={tx["git_problem"]}]#(~/dotfiles/scripts/tmux-git-status.sh "#{{pane_current_path}}")#[fg={tx["path"]}]#(~/dotfiles/scripts/tmux-git-bracket.sh close "#{{pane_current_path}}")#[fg={tx["text"]}] '
setw -g window-status-format '#[fg={tx["text"]}]#W'
setw -g window-status-current-format '#[fg={tx["current_window"]},bold]#W'
'''
with open(f"{home}/.tmux.palette.conf", "w") as f:
    f.write(tmux)

# 3) shell env for pygmentize + bat (bat theme colors below are generated too)
with open(f"{home}/.config/palette-env.sh", "w") as f:
    f.write("# Generated by scripts/theme.sh\nexport PYGMENTIZE_STYLE=%s\nexport BAT_THEME=%s\n" % (t["pygments"], t["name"]))

# 3b) bat .tmTheme generated from the nvim palette roles
roles = [
    ("comment", nv["muted"], "comment, punctuation.definition.comment"),
    ("keyword", nv["magenta"], "keyword, storage.modifier, storage.type.modifier"),
    ("function", nv["cyan"], "entity.name.function, support.function, meta.function-call"),
    ("type", nv["purple"], "entity.name.type, support.type, storage.type, meta.type"),
    ("string", nv["yellow"], "string, constant.other.symbol, meta.string"),
    ("number", nv["orange"], "constant.numeric, constant.language"),
    ("variable", nv["green"], "variable, entity.name.tag, entity.other.attribute-name, support.variable.property"),
]

def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;")

rows = '\n'.join(
    '    <dict>\n'
    '      <key>name</key><string>%s</string>\n'
    '      <key>scope</key><string>%s</string>\n'
    '      <key>settings</key><dict><key>foreground</key><string>%s</string></dict>\n'
    '    </dict>' % (title, esc(scope), esc(color))
    for title, color, scope in roles
)
theme_xml = f'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>{esc(t["name"])}</string>
  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>{esc(nv["fg"])}</string>
      </dict>
    </dict>
{rows}
  </array>
</dict>
</plist>
'''
bat_dir = f"{home}/.config/bat/themes"
os.makedirs(bat_dir, exist_ok=True)
with open(f"{bat_dir}/{t['name']}.tmTheme", "w") as f:
    f.write(theme_xml)

import shutil as _shutil
if _shutil.which("bat"):
    os.system("bat cache --build >/dev/null 2>&1")

# 4) opencode theme reference (opencode.json + tui.json + ocv-tui.json; live + repo)
oc_files = [
    f"{home}/.config/opencode/opencode.json",
    f"{repo}/config/opencode/opencode.json",
    f"{home}/.config/opencode/tui.json",
    f"{repo}/config/opencode/tui.json",
    f"{repo}/config/opencode/ocv-tui.json",
]
for path in oc_files:
    try:
        with open(path) as f:
            oc = json.load(f)
    except FileNotFoundError:
        continue
    oc["theme"] = t["opencode_theme"]
    with open(path, "w") as f:
        json.dump(oc, f, indent=2)
        f.write("\n")

# sync theme json files into the live opencode config
import shutil
themes_dst = f"{home}/.config/opencode/themes"
os.makedirs(themes_dst, exist_ok=True)
for tf in os.listdir(f"{repo}/config/opencode/themes"):
    if not tf.endswith(".json"):
        continue
    src, dst = f"{repo}/config/opencode/themes/{tf}", f"{themes_dst}/{tf}"
    if os.path.exists(dst) and os.path.samefile(src, dst):
        continue
    shutil.copy(src, dst)

# 5) Windows Terminal colorscheme
wt_path = "/mnt/c/Users/z005561w/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
with open(wt_path) as f:
    s = json.load(f)
scheme = {"name": t["wt_scheme"], "cursorColor": wt["foreground"]}
for key, val in {
    "background":"background","foreground":"foreground","black":"black","red":"red","green":"green",
    "yellow":"yellow","blue":"blue","purple":"purple","cyan":"cyan","white":"white",
    "brightBlack":"brightBlack","brightRed":"brightRed","brightGreen":"brightGreen","brightYellow":"brightYellow",
    "brightBlue":"brightBlue","brightPurple":"brightPurple","brightCyan":"brightCyan","brightWhite":"brightWhite",
    "selectionBackground":"selectionBackground",
}.items():
    if val in wt:
        scheme[key] = wt[val]
# Windows Terminal forks overrides into "Name (modified n)" duplicates whenever
# the UI touches settings; drop those duplicates before upserting the canonical scheme.
schemes = [x for x in s.get("schemes", []) if " (modified" not in x.get("name", "")]
modified_dropped = len(s.get("schemes", [])) - len(schemes)
s["schemes"] = schemes
for i, ex in enumerate(schemes):
    if ex.get("name") == t["wt_scheme"]:
        schemes[i] = scheme
        break
else:
    schemes.append(scheme)
for p in s.get("profiles", {}).get("list", []):
    if p.get("name") == "Ubuntu" and p.get("colorScheme"):
        p["colorScheme"] = t["wt_scheme"]
        p.setdefault("opacity", 85)
with open(wt_path, "w") as f:
    json.dump(s, f, indent=4)
PYEOF

tmux source-file "$HOME/.tmux.palette.conf" 2>/dev/null || true
echo "theme: $name (restart nvim + opencode to apply)"
