#!/usr/bin/env bash
# Switch the whole environment to a Catppuccin flavour.
# usuario: theme <dark|light> → dark = Catppuccin Mocha, light = Catppuccin Latte.
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo="$(CDPATH= cd -- "$script_dir/.." && pwd)"
name="${1:?usage: theme <dark|light>}"
data="$repo/color-schemes/$name.json"

[ -f "$data" ] || { echo "unknown theme: $name" >&2; exit 1; }

python3 - "$repo" "$data" <<'PYEOF'
import json, os, shutil, sys, urllib.request

repo, data_path = sys.argv[1], sys.argv[2]
home = os.path.expanduser("~")
config_home = os.environ.get("XDG_CONFIG_HOME", f"{home}/.config")
state_home = os.environ.get("XDG_STATE_HOME", f"{home}/.local/state")
wt_path = os.environ.get(
    "DOTFILES_WT_SETTINGS",
    "/mnt/c/Users/z005561w/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json",
)

with open(data_path) as f:
    t = json.load(f)
pal, flavour = t["palette"], t["flavour"]
catppuccin_flavours = ("latte", "mocha", "frappe", "macchiato")
bat_theme = t.get("bat_theme") or f"Catppuccin {flavour.capitalize()}"
oc_theme = t.get("opencode_theme") or f"catppuccin-{flavour}"

# 1) canonical runtime state
state_dir = f"{state_home}/dotfiles"
os.makedirs(state_dir, exist_ok=True)
with open(f"{state_dir}/theme", "w") as f:
    f.write(flavour + "\n")

# 2) shell env + fzf chrome from the official palette
def hx(k):
    return pal[k]

fzf_colors = ",".join([
    f"bg+:{pal['surface0']}",
    f"fg:{pal['text']}",
    f"fg+:{pal['text']}",
    f"query:{pal['text']}",
    f"hl:{pal['peach']}",
    f"hl+:{pal['peach']}:bold:underline",
    f"info:{pal['overlay1']}",
    f"prompt:{pal['blue']}",
    f"pointer:{pal['pink']}",
    f"marker:{pal['green']}",
    f"spinner:{pal['sapphire']}",
    f"header:{pal['overlay1']}",
    f"border:{pal['surface1']}",
    f"separator:{pal['surface1']}",
    f"preview-fg:{pal['text']}",
])
with open(f"{config_home}/palette-env.sh", "w") as f:
    f.write(
        "# Generated by scripts/theme.sh; do not edit by hand.\n"
        f'export CATPPUCCIN_FLAVOUR="{flavour}"\n'
        f'export DOTFILES_THEME="{oc_theme}"\n'
        f'export BAT_THEME="{bat_theme}"\n'
        f'export PYGMENTIZE_STYLE="ansi"\n'
        f'export FZF_COLORS="{fzf_colors}"\n'
    )

# 3) tmux palette overlay
tmux = f'''# Generated by scripts/theme.sh ({flavour}); do not edit by hand.
set -g status-style bg=default,fg='{pal["text"]}'
set -g window-status-style bg=default
set -g status-left '#[fg={pal["sapphire"]}]#S(#[fg={pal["green"]}]#(~/dotfiles/scripts/tmux-telemetry.sh)#[fg={pal["sapphire"]}])'
set -g status-right '#(~/dotfiles/scripts/tmux-repo-status.sh "#{{pane_current_path}}" "{pal["mauve"]}" "{pal["red"]}")'
setw -g window-status-format '#[fg={pal["overlay0"]}]#W'
setw -g window-status-current-format '#[fg={pal["blue"]},bold]#W'
'''
with open(f"{home}/.tmux.palette.conf", "w") as f:
    f.write(tmux)

# 4) bat themes: official Catppuccin downloads for catppuccin flavours,
# generated nv-* themes for custom (system-fun) schemes.
bat_dir = f"{config_home}/bat/themes"
os.makedirs(bat_dir, exist_ok=True)

if bat_theme.startswith("nv-"):
    roles = [
        ("comment", pal["overlay2"], "comment, punctuation.definition.comment"),
        ("keyword", pal["pink"], "keyword, storage.modifier, storage.type.modifier"),
        ("function", pal["sky"], "entity.name.function, support.function, meta.function-call"),
        ("type", pal["mauve"], "entity.name.type, support.type, storage.type, meta.type"),
        ("string", pal["yellow"], "string, constant.other.symbol, meta.string"),
        ("number", pal["peach"], "constant.numeric, constant.language"),
        ("variable", pal["green"], "variable, entity.name.tag, entity.other.attribute-name, support.variable.property"),
    ]

    def esc(s):
        return s.replace("&", "&amp;").replace("<", "&lt;")

    rows = "\n".join(
        '    <dict><key>name</key><string>%s</string>'
        '<key>scope</key><string>%s</string>'
        '<key>settings</key><dict><key>foreground</key><string>%s</string></dict></dict>'
        % (title, esc(scope), esc(color))
        for title, color, scope in roles
    )
    bg = t.get("ansi", {}).get("background", pal["base"])
    theme_xml = f'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key><string>{esc(bat_theme)}</string>
  <key>uuid</key><string>00000000-0000-0000-beef-000000000001</string>
  <key>settings</key>
  <array>
    <dict><key>settings</key><dict>
      <key>background</key><string>{esc(bg)}</string>
      <key>foreground</key><string>{esc(pal["text"])}</string>
    </dict></dict>
{rows}
  </array>
</dict>
</plist>
'''
    with open(f"{bat_dir}/{bat_theme}.tmTheme", "w") as f:
        f.write(theme_xml)
else:
    for uf in ("Latte", "Mocha"):
        dst = f"{bat_dir}/Catppuccin {uf}.tmTheme"
        if not os.path.exists(dst):
            url = f"https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20{uf}.tmTheme"
            try:
                urllib.request.urlretrieve(url, dst)
            except Exception as e:
                print(f"warning: bat theme download failed ({uf}): {e}", file=sys.stderr)

if shutil.which("bat"):
    os.system("bat cache --build >/dev/null 2>&1")

# 5) OpenCode — LIVE configs only; repo files stay the portable baseline
oc_files = [
    f"{config_home}/opencode/opencode.json",
    f"{config_home}/opencode/tui.json",
    f"{config_home}/opencode/ocv-tui.json",
]
for path in oc_files:
    try:
        with open(path) as f:
            oc = json.load(f)
    except FileNotFoundError:
        continue
    oc["theme"] = oc_theme
    with open(path, "w") as f:
        json.dump(oc, f, indent=2)
        f.write("\n")

# sync tracked OpenCode theme files into the live config
themes_src = f"{repo}/config/opencode/themes"
themes_dst = f"{config_home}/opencode/themes"
os.makedirs(themes_dst, exist_ok=True)
for tf in os.listdir(themes_src):
    if not tf.endswith(".json"):
        continue
    src, dst = f"{themes_src}/{tf}", f"{themes_dst}/{tf}"
    if os.path.exists(dst) and os.path.samefile(src, dst):
        continue
    shutil.copy(src, dst)

# 6) Windows Terminal — official Catppuccin scheme, fully opaque
if "ansi" in t:
    ansi_map = dict(t["ansi"])
else:
    ansi_map = {
        "background": pal["base"] if flavour == "mocha" else "#EFF1F5",
        "foreground": pal["text"],
        "black": pal["subtext1"] if flavour == "latte" else pal["surface1"],
        "red": pal["red"],
        "green": pal["green"],
        "yellow": pal["yellow"],
        "blue": pal["blue"],
        "purple": pal["mauve"],
        "cyan": pal["teal"],
        "white": pal["surface1"],
        "brightBlack": pal["overlay1"] if flavour == "latte" else pal["surface2"],
        "brightRed": pal["maroon"],
        "brightGreen": pal["green"],
        "brightYellow": pal["yellow"],
        "brightBlue": pal["lavender"],
        "brightPurple": pal["pink"],
        "brightCyan": pal["teal"],
        "brightWhite": pal["subtext1"],
        "selectionBackground": pal["surface0"],
    }
scheme = dict(ansi_map)
scheme["name"] = t.get("wt_scheme") or bat_theme
scheme["cursorColor"] = pal["text"]
wt_opacity = t.get("opacity", 100)

if os.path.exists(wt_path):
    with open(wt_path) as f:
        s = json.load(f)
    schemes = [x for x in s.get("schemes", []) if " (modified" not in x.get("name", "")]
    s["schemes"] = schemes
    for i, ex in enumerate(schemes):
        if ex.get("name") == scheme["name"]:
            schemes[i] = scheme
            break
    else:
        schemes.append(scheme)
    for p in s.get("profiles", {}).get("list", []):
        if p.get("name") == "Ubuntu":
            p["colorScheme"] = scheme["name"]
            p["opacity"] = wt_opacity
            p["useAcrylic"] = False
            for k in ("backgroundImage", "backgroundImageOpacity", "acrylicOpacity"):
                p.pop(k, None)
            if isinstance(p.get("unfocusedAppearance"), dict):
                p["unfocusedAppearance"]["opacity"] = wt_opacity
                p["unfocusedAppearance"]["useAcrylic"] = False
    defaults = s.get("profiles", {}).get("defaults", {})
    defaults["opacity"] = wt_opacity
    defaults["useAcrylic"] = False
    with open(wt_path, "w") as f:
        json.dump(s, f, indent=4)
else:
    print(f"warning: Windows Terminal settings not found at {wt_path}", file=sys.stderr)
PYEOF

tmux source-file "$HOME/.tmux.palette.conf" 2>/dev/null || true
echo "theme: $name (Catppuccin '$name'; restart nvim + opencode to apply)"
