-- Generated by scripts/theme.sh from themes/light.json; do not edit by hand.
return {
	variant = "light",
	fg = "#2d2d33",
	muted = "#8a8578",
	green = "#3e8f0e",
	cyan = "#0e7f95",
	yellow = "#945d00",
	orange = "#b54a00",
	magenta = "#c2259c",
	purple = "#7c3aed",
	red = "#d2404f",
	select = "#c9d7ea",
	linenr = "#9b9689",
}
