-- Generated by scripts/theme.sh from themes/latte.json; do not edit by hand.
return {
	variant = "light",
	fg = "#4c4f69",
	muted = "#8c8fa1",
	green = "#40a02b",
	cyan = "#209fb5",
	yellow = "#df8e1d",
	orange = "#fe640b",
	magenta = "#ea76cb",
	purple = "#8839ef",
	red = "#d20f39",
	select = "#ccd0da",
	linenr = "#acb0be",
}
