-- Generated by scripts/theme.sh from color-schemes/neon.json; do not edit by hand.
return {
	variant = "default",
	fg = "#e5e7eb",
	muted = "#8b7aa8",
	green = "#afff5f",
	cyan = "#5fd7ff",
	yellow = "#ffd75f",
	orange = "#ffaf5f",
	magenta = "#ff5fd2",
	purple = "#c084fc",
	red = "#ff5f87",
	select = "#515c7e",
	linenr = "#a0a8b7",
}
